# Generated by Django 5.2 on 2026-01-08 16:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contragent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('edrpou', models.CharField(max_length=10, verbose_name='ЄДРПОУ')),
                ('manager', models.CharField(max_length=100, verbose_name='Менеджер')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='user_documents/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Назва документа'),
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Номер договору')),
                ('region', models.CharField(max_length=100, verbose_name='Область/Регіон')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('contragent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.contragent', verbose_name='Контрагент')),
            ],
        ),
    ]
