# Generated by Django 5.2 on 2026-01-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_contragent_document_uploaded_at_alter_document_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='agreements/'),
        ),
    ]
