# Generated by Django 5.2 on 2026-01-08 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_agreement_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AddField(
            model_name='contragent',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contragent', to=settings.AUTH_USER_MODEL, verbose_name='Користувач (Клієнт)'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='contragent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='accounts.contragent', verbose_name='Контрагент'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='agreements/', verbose_name='Файл договору'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='region',
            field=models.CharField(default='Не вказано', max_length=100, verbose_name='Область/Регіон'),
        ),
        migrations.AlterField(
            model_name='contragent',
            name='edrpou',
            field=models.CharField(max_length=10, unique=True, verbose_name='ЄДРПОУ'),
        ),
    ]
