# Generated by Django 5.2 on 2026-01-08 19:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_document_contragent_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='date_created',
        ),
        migrations.AddField(
            model_name='agreement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agreement',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата підписання'),
        ),
    ]
