# Generated by Django 5.2 on 2026-01-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_agreement_date_created_agreement_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва файлу')),
                ('document_type', models.CharField(choices=[('Договір', 'Договір'), ('Акт', 'Акт'), ('Рахунок', 'Рахунок'), ('Динаміка обсягів споживання', 'Динаміка обсягів споживання'), ('Додаткова угода', 'Додаткова угода'), ('Перелік ЕІС-кодів', 'Перелік ЕІС-кодів'), ('Повідомлення', 'Повідомлення'), ('Інше', 'Інше')], default='Інше', max_length=100, verbose_name='Тип документа')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TariffDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Рік')),
                ('name', models.CharField(max_length=255, verbose_name='Назва тарифу')),
                ('file', models.FileField(blank=True, null=True, upload_to='tariffs/', verbose_name='Файл тарифу')),
            ],
        ),
    ]
