# Generated by Django 5.2 on 2026-01-12 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_document_tariffdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='contragent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.contragent', verbose_name='Контрагент'),
        ),
    ]
