# Generated by Django 5.2 on 2025-11-19 12:18

import pyuploadcare.dj.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('file', pyuploadcare.dj.models.FileField()),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=pyuploadcare.dj.models.FileField(),
        ),
    ]
