# Generated by Django 5.2 on 2025-11-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                # ЗАМІНЕНО: pyuploadcare.dj.models.FileField() -> models.FileField()
                ('file', models.FileField(upload_to='tariffs/')), 
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            # ЗАМІНЕНО: pyuploadcare.dj.models.FileField() -> models.FileField()
            field=models.FileField(upload_to='documents/'),
        ),
    ]