# Generated by Django 5.2 on 2025-11-19 12:24

import pyuploadcare.dj.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tariffdocument_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=pyuploadcare.dj.models.FileField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tariffdocument',
            name='file',
            field=pyuploadcare.dj.models.FileField(blank=True, null=True),
        ),
    ]
