# Generated by Django 5.2 on 2025-11-19 12:24

from django.db import migrations, models # Додай models сюди, якщо його немає


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tariffdocument_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='tariffdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='tariffs/'),
        ),
    ]