# Generated by Django 5.2 on 2026-01-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_document_file_alter_tariffdocument_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документи'},
        ),
        migrations.AlterModelOptions(
            name='tariffdocument',
            options={'verbose_name': 'Тарифний документ', 'verbose_name_plural': 'Тарифні документи'},
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('Договір', 'Договір'), ('Акт', 'Акт'), ('Рахунок', 'Рахунок'), ('Динаміка обсягів споживання', 'Динаміка обсягів споживання'), ('Додаткова угода', 'Додаткова угода'), ('Перелік ЕІС-кодів', 'Перелік ЕІС-кодів'), ('Повідомлення', 'Повідомлення'), ('Інше', 'Інше')], default='Інше', max_length=100, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Назва файлу'),
        ),
        migrations.AlterField(
            model_name='tariffdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='tariffs/', verbose_name='Файл тарифу'),
        ),
        migrations.AlterField(
            model_name='tariffdocument',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Назва тарифу'),
        ),
        migrations.AlterField(
            model_name='tariffdocument',
            name='year',
            field=models.IntegerField(verbose_name='Рік'),
        ),
    ]
