# Generated by Django 5.2 on 2026-01-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_document_options_alter_tariffdocument_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tariffdocument',
            options={},
        ),
        migrations.RemoveField(
            model_name='document',
            name='document_type',
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tariffdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='tariffs/'),
        ),
        migrations.AlterField(
            model_name='tariffdocument',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tariffdocument',
            name='year',
            field=models.IntegerField(),
        ),
    ]
